import json

def extract_text_by_page(document_json):
    """
    Extracts the text from the Document AI JSON output and associates it with each page.

    Args:
    - document_json: JSON data from Google Document AI output.

    Returns:
    - A dictionary containing text for each page.
    """
    full_text = document_json['text']  # This contains the full text of the document

    # Initialize the output dictionary
    output_data = {"pages": []}

    # Loop through each page in the document
    for page_num, page in enumerate(document_json['pages']):
        page_text = ""

        # Loop through the blocks in each page
        for block in page['blocks']:
            # Extract text using the text segments (anchors) in the block layout
            if 'textAnchor' in block['layout'] and 'textSegments' in block['layout']['textAnchor']:
                for segment in block['layout']['textAnchor']['textSegments']:
                    start_idx = int(segment.get('startIndex', 0))  # Start index defaults to 0 if missing
                    end_idx = int(segment.get('endIndex', len(full_text)))  # End index defaults to the length of the text
                    page_text += full_text[start_idx:end_idx] + " "  # Add space between blocks for readability

        # Store the page number and its text
        output_data["pages"].append({
            "page_number": page_num + 1,
            "text": page_text.strip()  # Remove leading/trailing whitespace
        })

    return output_data

# Load the JSON file generated by Google Cloud Document AI
with open('document_output.json', 'r') as file:
    document_json = json.load(file)

# Extract text by page
extracted_data = extract_text_by_page(document_json)

# Save the segmented text into a new JSON file
with open('segmented_output.json', 'w') as output_file:
    json.dump(extracted_data, output_file, indent=4)

print("Text segmented by page has been saved to segmented_output.json")
